logging:
  level:
    com.kholodilin.outbox: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        enabled: false
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
          timeout: 2s

spring:
  kafka:
    consumer:
      group-id: notification-stub-dev
