spring:
  application:
    name: notification-stub
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    listener:
      observation-enabled: true
    consumer:
      group-id: notification-stub
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.kholodilin.outbox.events
        spring.json.value.default.type: com.kholodilin.outbox.events.EventEnvelope
      max-poll-records: 100

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  tracing:
    enabled: ${TRACING_ENABLED:true}
    sampling:
      probability: ${TRACING_SAMPLING:1.0}
    propagation:
      type: w3c
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}

logging:
  level:
    root: INFO
    com.kholodilin.outbox: INFO

app:
  kafka:
    topic: orders.events
    batch-listener: true

server:
  port: 8081
