--liquibase formatted sql

--changeset outbox:001-orders
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (customer_id, id)
) PARTITION BY HASH (customer_id);

--changeset outbox:001-orders-partitions splitStatements:false
DO $$
BEGIN
    FOR i IN 0..9 LOOP
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS orders_p%s PARTITION OF orders FOR VALUES WITH (MODULUS 10, REMAINDER %s)',
            i, i
        );
    END LOOP;
END $$;
