--liquibase formatted sql

--changeset outbox:003-idempotency-keys
CREATE TABLE idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status INT NOT NULL, -- 0=PROCESSING, 1=COMPLETED, 2=FAILED
    response_body JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (customer_id, id),
    CONSTRAINT uq_idempotency_customer_key UNIQUE (customer_id, idempotency_key)
) PARTITION BY HASH (customer_id);

--changeset outbox:003-idempotency-partitions splitStatements:false
DO $$
BEGIN
    FOR i IN 0..9 LOOP
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS idempotency_keys_p%s PARTITION OF idempotency_keys FOR VALUES WITH (MODULUS 10, REMAINDER %s)',
            i, i
        );
    END LOOP;
END $$;
