--liquibase formatted sql

--changeset outbox:004-outbox-events
CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    payload JSONB NOT NULL,
    status INT NOT NULL, -- active: 0=NEW, 1=PROCESSING, 2=FAILED; archive: 101=DEAD, 110=SENT
    retry_count INT NOT NULL DEFAULT 0,
    locked_by VARCHAR(128),
    locked_until TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (status, id)
) PARTITION BY RANGE (status);

CREATE INDEX idx_outbox_status_locked_until ON outbox_events (status, locked_until);

--changeset outbox:004-outbox-events-partitions splitStatements:false
CREATE TABLE outbox_events_active PARTITION OF outbox_events
    FOR VALUES FROM (0) TO (100);

CREATE TABLE outbox_events_archive PARTITION OF outbox_events
    FOR VALUES FROM (100) TO (MAXVALUE);
