--liquibase formatted sql

--changeset outbox:004-outbox-events
CREATE TABLE outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aggregate_id VARCHAR(128) NOT NULL,
    partition_key VARCHAR(128) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    payload JSONB NOT NULL,
    headers JSONB,
    status INT NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    locked_by VARCHAR(128),
    locked_until TIMESTAMPTZ,
    trace_parent TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (status, id)
) PARTITION BY RANGE (status);

CREATE INDEX idx_outbox_events_status_locked_until ON outbox_events (status, locked_until);

--changeset outbox:004-outbox-events-partitions splitStatements:false
CREATE TABLE outbox_events_active
    PARTITION OF outbox_events
    FOR VALUES FROM (MINVALUE) TO (100);

CREATE TABLE outbox_events_archive
    PARTITION OF outbox_events
    FOR VALUES FROM (100) TO (MAXVALUE);
