logging:
  level:
    com.kholodilin.outbox: DEBUG

app:
  rate-limit:
    global:
      capacity: 50000
      refill-per-second: 5000
    per-customer:
      capacity: 5000
      refill-per-second: 1000
    per-ip:
      capacity: 2000
      refill-per-second: 500
