apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      tracesToLogsV2:
        datasourceUid: prometheus
      search:
        hide: false
      streamingEnabled:
        search: false
        metrics: false
